# Autogenerated config.py
#
# NOTE: config.py is intended for advanced users who are comfortable
# with manually migrating the config file on qutebrowser upgrades. If
# you prefer, you can also configure qutebrowser using the
# :set/:bind/:config-* commands without having to write a config.py
# file.
#
# Documentation:
#   qute://help/configuring.html
#   qute://help/settings.html

# Change the argument to True to still load settings configured via autoconfig.yml
config.load_autoconfig(False)

# default config moved to default.py
# Loading all config
import os

# Initialize qutebrowser config
c = c  # noqa: F821

# Function to execute the content of a file and update the config
def execute_files_in_directory(directory):
    for filename in os.listdir(directory):
        if filename.endswith('.py') and filename != '__init__.py':
            file_path = os.path.join(directory, filename)
            with open(file_path) as f:
                exec(f.read(), globals(), {'c': c})

# Import modularized configurations from config_modules directory
execute_files_in_directory(os.path.join(os.path.dirname(__file__), 'config_modules'))
